### ISSUE TITLE
Doesn't work in iOS 10

### ISSUE THREAD

**Issue by b9874e** [alongubkin/audiotoggle#17]
Hy the plugin doesn't work in iOS 10 is it possible to update it?

**Comment by VitorRiyuzo** [comment]
I have the same problem

**Comment by stefanhuber** [comment]
have you got it working on ios 10?

**Comment by nice2seeu** [comment]
In my setting, the plugin works on ios 10. Although 'cordova plugin add https://github.com/alongubkin/audiotoggle.git --save' did not work, I directly downloaded and installed it.
