### ISSUE TITLE
How do i use this in ionic Framework?

### ISSUE THREAD

**Issue by zzzet** [alongubkin/audiotoggle#7]
I tried to use like cordova.plugins.audiotoggle.setAudioMode but its not working.

**Comment by muhsin-k** [comment]
How to use this in our controller?

**Comment by LTroya** [comment]
I use this on my project:

Earpiece mode:

```
AudioToggle.setAudioMode(AudioToggle.EARPIECE);
```

Speaker mode:

```
AudioToggle.setAudioMode(AudioToggle.SPEAKER);
```

You only need to install it

```
cordova plugin add com.dooble.audiotoggle
```

No dependency injection, just use it in your controllers.

**Comment by GulinSS** [comment]
@LTroya  :+1:

**Comment by sidharth016** [comment]
It works very dubiously. Build fails as controllers cannot identify AudioToggle

**Comment by basinmax** [comment]
> It works very dubiously. Build fails as controllers cannot identify AudioToggle

cordova plugin add com.dooble.audiotoggle

page:

import *********;

declare var AudioToggle;

@Component({....
