### ISSUE TITLE
switch to speakerPhone fails on IOS after switching to IOS9

### ISSUE THREAD

**Issue by Elpetro** [alongubkin/audiotoggle#8]
I'm using audiotoggle on an ionic project.
It seems that switching to Speakerphone fails since I upgraded phone to IOS9, and I see no error msg in xcode console.
Has anyone successfully experienced the pugin on IOS9?

**Comment by manur** [comment]
`'AudioSessionSetProperty' is deprecated: first deprecated in iOS 7.0`

Looks like Apple has turned off support for this method after 2 major iOS versions of deprecation support. Sort of consistent with how they deprecate other things.

That said, I don't have another cordova plugin that works as easily as this one.

**Comment by manur** [comment]
@alongubkin -- is there an update that can be applied to support iOS9? It looks like iOS8+ involves getting some app-level context object, but I'm not an expert with the framework. Would appreciate an update.

**Comment by Elpetro** [comment]
Fixed when installing latest version of plugin  instead of using _cordova plugin add audiotoggle_
